name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install
      - run: yarn lint
      - run: yarn lint:ts
      - run: yarn build
      - run: yarn test --ci
      - run: yarn test:tsd
